language: php
php:
  - 7.2
  - 7.3
services:
  - mysql
  - redis
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  # Create DB for testing.
  - mysql -u root -e 'CREATE DATABASE shieldon_unittest;'
  - mysql -u root -e "CREATE USER 'shieldon'@'localhost' IDENTIFIED BY 'taiwan';"
  - mysql -u root -e "GRANT ALL ON shieldon_unittest.* TO 'shieldon'@'localhost';"
script: composer test