name: PHP Composer

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ 2.x ]

jobs:
  run:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          operating-system: [ubuntu-16.04]
          php-versions: ['7.1', '7.2', '7.3']
      name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

      services:
 
        mysql:
          image: mysql:5.7
          env:
            MYSQL_USER: shieldon
            MYSQL_PASSWORD: taiwan
            MYSQL_DATABASE: shieldon_unittest
            MYSQL_ROOT_PASSWORD: taiwan
          ports:
            - 3306/tcp
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        redis:
          image: redis
          ports:
            - 6379/tcp
          options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP
          uses: shivammathur/setup-php@v1
          with:
            php-version: ${{ matrix.php-versions }}
            extensions: mbstring, pdo, pdo_mysql, intl, zip, redis
            coverage: none

        - name: Install dependencies
          run: composer install --prefer-dist --no-interaction --dev

        - name: Update packages
          run: composer self-update

        - name: Run tests.
          run: composer test
