name: PHP Composer

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ 2.x ]

jobs:
  run:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          operating-system: [ubuntu-16.04]
          php-versions: ['7.1', '7.2', '7.3']
      name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

      services:
 
        mysql:
          image: mysql:5.7
          env:	
            MYSQL_USER: shieldon	
            MYSQL_PASSWORD: taiwan	
            MYSQL_DATABASE: shieldon_unittest	
            MYSQL_ROOT_PASSWORD: taiwan
          ports:
            - 3306/tcp
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        redis:
          image: redis
          ports:
            - 6379/tcp
          options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP with Xdebug
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}
            extensions: mbstring, pdo, pdo_mysql, intl, zip, redis, ctype, json
            coverage: xdebug
       
        - name: Create a folder for testing.
          run: sudo mkdir /home/runner/work/shieldon/shieldon/tmp
        
        - name: Make folder writable.
          run: sudo chmod 777 /home/runner/work/shieldon/shieldon/tmp
            
        - name: Start mysql service.
          run: sudo /etc/init.d/mysql start
          
        - name: Mysql - Create database.
          run: sudo mysql -u root -e 'CREATE DATABASE shieldon_unittest;'

        - name: Mysql - Create user.
          run: sudo mysql -u root -e "CREATE USER 'shieldon'@'localhost' IDENTIFIED BY 'taiwan';"
          
        - name: Mysql - Grant permission.
          run: sudo mysql -u root -e "GRANT ALL ON shieldon_unittest.* TO 'shieldon'@'localhost';"
  
        - name: Install dependencies
          run: composer install --prefer-dist --no-interaction --dev

        - name: Update packages
          run: composer self-update

        - name: Run tests.
          run: composer test
