name: PHP Composer

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ 2.x ]

jobs:
  run:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          operating-system: [ubuntu-16.04]
          php-versions: ['7.1', '7.2', '7.3']
      name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP
          uses: shivammathur/setup-php@v1
          with:
            php-version: ${{ matrix.php-versions }}
            extensions: mbstring, pdo, pdo_mysql, intl, zip, redis
            coverage: none

        - name: Install dependencies
          run: composer install --prefer-dist --no-interaction --dev

        - name: Update packages
          run: composer self-update

        - name: Create DB.
          run: mysql -u root -e 'CREATE DATABASE shieldon_unittest;'

        - name: Create user.
          run: mysql -u root -e "CREATE USER 'shieldon'@'localhost' IDENTIFIED BY 'taiwan';"

        - name: Grant permission.
          run: -u root -e "GRANT ALL ON shieldon_unittest.* TO 'shieldon'@'localhost';"

        - name: Run tests.
          run: composer test
